spring:
  profiles:
    active:
    - dev

---
spring:
  profiles: dev     #开发环境
  application:
    name: microservicecloud-config-lox-dev
    
---
spring:
  profiles: test  #测试环境
  application:
    name: microservicecloud-config-lox-test
    
#注意编码 utf-8    
